### PR TITLE
Add LICENSE.md

### LINKED ISSUE #29: What is the License for this project?
I am compiling a report on 3rd party library usage at my company and noticed that broadcaster doesn't have a LICENSE file.

### PR DESCRIPTION
**Pull request by rafalp**
Adds standard Encode's license to this repo

Fixes #29

### CODE REVIEW

**Review by euri10 — APPROVED** [review]

**Comment by tomchristie** [comment]
As the legal copyright holder I'm confirming that I'm okay with the project using this licensing, yup.

**Comment by euri10** [comment]
> As the legal copyright holder I'm confirming that I'm okay with the project using this licensing, yup.

oups, I probably should have waited to approve or even not do it at all, but since it was a copy paste of the other licences I felt it was ok: I apologize if I stepped on your shoes !

**Comment by tomchristie** [comment]
No need to apologize. I'm just being formal about okay'ing it. 😃👍

**Comment by euri10** [comment]
> No need to apologize. I'm just being formal about okay'ing it.

ok I'm formally more relaxed now :+1:

**Pull request merged**
