### PR TITLE
Redis Backend Password support

### PR DESCRIPTION
**Pull request by k1dave6412**

### CODE REVIEW

**Comment by hramezani** [comment]
Hi @k1dave6412 , Could you please add a test for this patch?

**Comment by tomchristie** [comment]
Actually I’m pretty okay with changes like this one *not* adding extra test cases, since they end up being:

Code: “Call this function with this new argument”
Test: “Test that the code called the function with this new argument”

Which doesn’t actually need to add a lot of value.

**Comment by k1dave6412** [comment]
@hramezani I added the simple test

**Comment by hramezani** [comment]
> Actually I’m pretty okay with changes like this one _not_ adding extra test cases, since they end up being:
> 
> Code: “Call this function with this new argument”
> Test: “Test that the code called the function with this new argument”
> 
> Which doesn’t actually tend to add a lot of value.

@tomchristie  Thanks for the explanation. I agree with you.

@k1dave6412 Sorry, we don't need the test. Please remove it.

**Comment by k1dave6412** [comment]
@hramezani Ok, I remove it

**Comment by k1dave6412** [comment]
@hramezani  When will the PR be merged?

**Comment by hramezani** [comment]
@k1dave6412 I am not a merger of this project. let's wait for @tomchristie to merge it. I believe he will do that when he has time.

**Comment by lbatteau** [comment]
@tomchristie can you please review and merge this PR, it's a very simple fix and a huge blocker right now. 🙏

**Comment by lbatteau** [comment]
If anyone's interested in using Redis directly like me, here's how. https://medium.com/deepdesk/server-sent-events-in-fastapi-using-redis-pub-sub-eba1dbfe8031. Full gist: https://gist.github.com/lbatteau/1bc7ae630d5b7844d58f038085590f97.

**Comment by Kludex** [comment]
I don't know how to checkout on fork's master branch locally, and I needed to apply black here... So I've created https://github.com/encode/broadcaster/pull/79 - co-author trailer is added there.

- Closing this in favor of #79.

**Pull request closed without merging**
